apiVersion: v1
kind: Service
metadata:
  name: heart-api
  labels:
    app: heart-api
spec:
  selector:
    app: heart-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
